from modules.features import Features
from modules.downloader import Download
from modules.navigation import Navigation
from modules.detections import Detection
from modules.components import Components
from modules.maskrcnn import MaskRcnn
from modules.cartoons import Cartoons
from modules.removeBg import RemoveBg
from modules.sendEmail import SendEmail
